#+TITLE: Data and Analysis for "The Quick and the Dead"
#+AUTHOR: Colin S. Maxwell and Paul M. Magwene
#+DATE: June 2016


* Introduction

This document describes the data submitted to the Dryad repository for
the paper "The Quick and the Dead: Microbial Demography at the Yeast
Thermal Limit" and provides links to the code used to generate figures
and the statistical analysis in the paper. 

* Requirements

The scripts and data files should all be in the same folder. 

* Files in this submission

This section contains a list of the data files included in this
submission and gives:

1) A brief description of how the data were generated
2) The name of the script (if any) that produced the data
3) A description of the column names in the data

** 2016-Maxwell-Magwene-100genomes-temperature-growth.csv

This is a summary file that gives estimates of the maximum population
growth rate of a strain for several replicates and several
temperatures. This file was generated by [[file:process-growth-curves.R]],
which processes the raw data that is summarized in
[[file:2016-Maxwell-Magwene-100genomes-temperatures-raw.csv]].

------------------------------------------------------------

- fn :: This gives the path to the raw data file used to generate the
     estimate
- temp :: The temperature that the growth curve was collected at
- rep :: The replicate number of the temperature
- row :: The row that the well was in
- col :: The column that the well was in
- Strain :: The YJM number of the strain. YJM stands for 'Yeast John
     McCusker'. These are the original stocks for the 100 genomes
     collection used throughout these experiments that the PMY numbers
     are derived from
- PMY :: The PMY number of the strain. PMY stands for 'Paul Magwene
     Yeast'. These are the actual stocks used during these experiments.
- maxGrowth :: The estimate of maximum population growth for that
     strain and temperature, given in OD/sec
- pointOfMaxGrowthRate :: The time point at which the maximum OD was
     reached
- maxOD :: The maximum OD that was reached during the experiment

** 2016-Maxwell-Magwene-100genomes-temperatures-raw.csv

This file contains the raw OD measurements from the Tecan Sunrise
plate reader. The Tecan exports data in a form that is difficult to
analyze, so rather than including the raw .asc files, the data was
read in and aggregated by the script [[file:process-growth-curves.R]]. To
get the actual raw data in the script, please email the corresponding
author of the paper.

------------------------------------------------------------

- YJM :: The YJM number of the strain. YJM stands for 'Yeast John
     McCusker'. These are the original stocks for the 100 genomes
     collection used throughout these experiments that the PMY numbers
     are derived from
- PMY :: The PMY number of the strain. PMY stands for 'Paul Magwene
     Yeast'. These are the actual stocks used during these experiments.
- filename :: The path to the original raw data file
- platemap :: The path to the original plate map file.
- replicate :: The replicate number of the temperature
- temperature :: The temperature the growth curve was collected at
- row :: The row in the plate
- col :: The column in the plate
- seconds :: The number of seconds elapsed since the start of the experiment
- OD :: The optical density in the well

** 2016-Maxwell-Magwene-mito-morphology-scoring.csv

These data were collected by manually scoring the mitochondrial
morphology of strains containing a mitochondrially localized GFP at
both 30C and 35.5C in 'real time' (no images collected) in an Axio Imager.

See volume 5 pgs 12 and 14 of Colin Maxwell's lab notebook for the raw
data.

------------------------------------------------------------

- strain :: The CMY number of the strain. CMY stands for Colin Maxwell
     Yeast. see Table S1 for a mapping to the PMY number and genotype
     of the strain.
- temp :: The temperature that the data were collected at
- rep :: The replicate number of the data
- A_threads :: "A" is the original scoring code. "threads" is the
     morphology category.
- C_clumps :: "C" is the original scoring code. "clumps" is the
     morphology category; only clumpy mitochondria present.
- B_clumps-threads :: "B" is the original scoring 
     code. "clumps-threads" is the morphology category; both clumps
     and threads present.
- D_no-mitos :: "D" is the original scoring code. "no-mitos" is the
     morphology category; no mitochondria were observed.

** 2016-Maxwell-Magwene-mito-trackscar.csv

This contains data about the morphology and fecundity of several
strains of yeast at both 30C and 35.5C. These data were collected
using the DeltaVision and then scoring the morphology and counting the
budscars based on the resulting images. The file was generated from
the original count data files from the script
[[file:process-mito-trackscar-data.R]]. To get the actual raw data in the
script, please email the corresponding author of the paper.

------------------------------------------------------------

+ folder :: The name of the folder containing the original data
+ experiment_ID	:: The experiment ID of the data
+ counts_file :: The name of the file containing the original data
+ sampling :: The method of sampling used -- either "random" or
     "for_age". "Random" means the cells were imaged by moving in a
     transect along the slide and imaging each cell that was positive
     for the first stain. "for_age" means that older cells were sought
     out specifically. 
+ temp :: The temperature that the data was collected at.
+ media :: The media that the cells were grown in 
+ who_counted :: Who counted the buds (CSM = Colin S. Maxwell)
+ number_of_colors :: Either "2" or "3" color TrackScar
+ time :: Hours between stains
+ strain :: CMY (Colin Maxwell Yeast) number and the temperature. See
     Table S1 for a mapping from CMY numbers to other data.
+ growth :: Number of new scars produced during the experiment (should
     be called 'fecundity', but is called 'growth' for historical
     reasons). growth = second - first
+ first	:: Number of scars stained with the first stain
+ second :: The number of scars stained with the second stain.
+ mitos :: The mito morphology class of the cell: 't' = threads; 'c' =
     clumps; 'tc' = thread & clumps; 'n' = no mitochondria.

** 2016-Maxwell-Magwene-three-color-trackscar.csv

This contains the data for the three color trackscar experiments that
were analyzed during the experiment. The original design of these
experiments let recover after heat stress at either 30C or 37C for
either 3 or 6 hrs. The 3hr recovery data was not used in the paper and
is not included in this file. The 37C recovery data is only used for
its first interval as a two color TrackScar experiment. This file was
generated from the original count data files by the script
[[file:process-three-color-trackscar.R]]. To get the actual raw data in
the script, please email the corresponding author of the paper.

------------------------------------------------------------

- folder :: The name of the folder containing the original data
- counts_file :: The name of the file containing the original data
- experiment :: The experiment ID of the data
- sampling :: The method of sampling used -- either "random" or
     "for_age". "Random" means the cells were imaged by moving in a
     transect along the slide and imaging each cell that was positive
     for the first stain. "for_age" means that older cells were sought
     out specifically.
- who_counted :: Who counted the buds (CSM = Colin S. Maxwell)
- temp :: The temperature that the data was collected at.
- strain :: The PMY (Paul Magwene Yeast) number of the strain. For a
     mapping to YJM numbers reported in the text, see the file
     [[file:PMY_to_YJM.csv]].
- growth :: Number of new scars produced during the experiment (should
     be called 'fecundity', but is called 'growth' for historical
     reasons). growth = last - first
- growth1 :: Number of buds between the first and second stain
- growth2 :: Number of buds between the second and third stain
- first :: Number of scars stained with the first stain
- last :: Number of scars stained with the third stain
- recoveryTemp :: The temperature the cells were incubated in during
     the recovery period
- recoveryTime :: The length of time the cells were incubated during
     the recovery period.

** 2016-Maxwell-Magwene-two-color-trackscar-timeseries.csv

This data is two color TrackScar experiments where the time between
the first and the second stain varied between one and six hours. The
file was created by the script [[file:process-two-color-trackscar.R]]. To
get the actual raw data in the script, please email the corresponding
author of the paper.

------------------------------------------------------------

- folder :: The name of the folder containing the original data
- experiment_ID	::  The experiment ID of the data
- counts_file :: The name of the file containing the original data
- sampling :: The method of sampling used -- either "random" or
     "for_age". "Random" means the cells were imaged by moving in a
     transect along the slide and imaging each cell that was positive
     for the first stain. "for_age" means that older cells were sought
     out specifically.
- temp :: The temperature that the data was collected at.
- media :: The media that the cells were grown in 
- who_counted :: Who counted the buds (CSM = Colin S. Maxwell)
- number_of_colors ::  Either "2" or "3" color TrackScar
- time :: How many hours between the first and second strains
- strain :: The YJM number of the strain. YJM stands for 'Yeast John
     McCusker'. These are the original stocks for the 100 genomes
     collection used throughout these experiments that the PMY numbers
     are derived from
- replicate :: Replicate number
- growth :: Number of new scars produced during the experiment (should
     be called 'fecundity', but is called 'growth' for historical
     reasons). growth = second - first
- first	:: Number of scars stained with the first stain
- last :: The number of scars stained with the second stain.

** 2016-Maxwell-Magwene-two-color-trackscar.csv

These data are two color TrackScar experiments where the time between
the first and the second stain is six hours. The file was created by
the script [[file:process-two-color-trackscar.R]]. To get the actual raw
data in the script, please email the corresponding author of the
paper.

------------------------------------------------------------

- folder :: The name of the folder containing the original data
- experiment_ID	::  The experiment ID of the data
- counts_file :: The name of the file containing the original data
- sampling :: The method of sampling used -- either "random" or
     "for_age". "Random" means the cells were imaged by moving in a
     transect along the slide and imaging each cell that was positive
     for the first stain. "for_age" means that older cells were sought
     out specifically.
- temp :: The temperature that the data was collected at.
- media :: The media that the cells were grown in 
- who_counted :: Who counted the buds (CSM = Colin S. Maxwell)
- number_of_colors ::  Either "2" or "3" color TrackScar
- time :: How many hours between the first and second strains
- strain :: The PMY (Paul Magwene Yeast) number of the strain. For a
     mapping to YJM numbers reported in the text, see the file
     [[file:PMY_to_YJM.csv]].
- replicate :: Replicate number
- growth :: Number of new scars produced during the experiment (should
     be called 'fecundity', but is called 'growth' for historical
     reasons). growth = second - first
- first	:: Number of scars stained with the first stain
- last :: The number of scars stained with the second stain.

** heat-stress-candidates.csv

This is a file that gives a list of the strains sensitive to growth at
35.5C that were examined using TrackScar. The file was originally
produced by the script [[file:analyze-growth-curves.R]], but the name was
changed and was annotated when it became apparent that some strains
couldn't be analyzed using TrackScar. 

------------------------------------------------------------

- PMY :: The PMY (Paul Magwene Yeast) number of the strain. For a
     mapping to YJM numbers reported in the text, see the file
     [[file:PMY_to_YJM.csv]].
- ratioMaxGrowth :: Growth at 35.5C/30C
- maxGrowth30C :: Growth rate at 30C
- maxGrowth35halfC :: Growth rate at 35.5C
- maxGrowth37C :: Growth rate at 37C
- exclusion_reason :: If it was excluded from subsequent analysis, why?

** PMY_to_YJM.csv

This is a mapping between the 100 genomes PMY (Paul Magwene Yeast)
numbers and YJM (Yeast John McCusker) numbers.

------------------------------------------------------------

- PMY :: The PMY number
- Strain :: The YJM number

* Scripts used to generate the data files

All scripts that begin with the name 'process' were run to generate
data for the Dryad submission using files that will not be submitted
to Dryad. The scripts filter data to contain only the data needed in
the paper and annotate it with the appropriate metadata. Since these
scripts rely on unsubmitted data, they cannot be run but are submitted
to allow the data processing steps to be examined. See above for which
scripts generated which files.

- [[file:process-growth-curves.R]]
- [[file:process-mito-trackscar-data.R]]
- [[file:process-two-color-trackscar.R]]
- [[file:process-three-color-trackscar.R]]

* Miscellaneous code

- [[file:budscar-count-utilities.R]] :: Miscellaneous files for handling
     trackscar data
- [[file:fig-theme.R]] :: A ggplot2 theme used in the figures
- [[file:load-libraries.R]] :: Loads all the libraries used in the analysis
- [[file:tecan.R]] :: Functions to deal with the awful ASCII export from a
     Tecan Sunrise.

* Scripts used to create shared data sets

All scripts that begin with the name 'analyze' are used to process
data in a way that gets reused across multiple figures or code
blocks. They will all run as self-contained scripts, but most don't
generate  output, they just make certain datasets available.

- [[file:analyze-growth-curves]]
- [[file:analyze-linear-models.R]]
- [[file:analyze-S288C-trackscar.R]]
- [[file:analyze-three-color-trackscar.R]]
- [[file:analyze-two-color-trackscar.R]]

* Scripts used to generate figures

- [[file:generate-figures.R]]
- [[file:figure-2.R]]
- [[file:figure-3.R]]
- [[file:figure-4.R]]
- [[file::figure-5.R]]
- [[file:figure-6.R]]
- [[file:figure-S1.R]]
- [[file:figure-S2.R]]
- [[file:figure-S3.R]]
- [[file:figure-S4.R]]
- [[file:figure-S5.R]]
- [[file:figure-S6.R]]
- [[file:figure-S7.R]]
