#+TITLE: Data for "The Quick and the Dead"
#+AUTHOR: Colin S. Maxwell and Paul M. Magwene
#+DATE: June 2016


* Introduction

This document describes the data submitted to the Dryad repository for
the paper "The Quick and the Dead: Microbial Demography at the Yeast
Thermal Limit" and provides links to the code used to generate figures
and the statistical analysis in the paper. 

* Files in this submission



** 2016-Maxwell-Magwene-100genomes-temperature-growth.csv

This is a summary file that gives estimates of the maximum population
growth rate of a strain for several replicates and several
temperatures. This file was generated by [[file:process-growth-curves.R]],
which processes the raw data that is summarized in
[[file:2016-Maxwell-Magwene-100genomes-temperatures-raw.csv]].

------------------------------------------------------------

- fn :: This gives the path to the raw data file used to generate the
     estimate
- temp :: The temperature that the growth curve was collected at
- rep :: The replicate number of the temperature
- row :: The row that the well was in
- col :: The column that the well was in
- Strain :: The YJM number of the strain. YJM stands for 'Yeast John
     McCusker'. These are the original stocks for the 100 genomes
     collection used throughout these experiments that the PMY numbers
     are derived from
- PMY :: The PMY number of the strain. PMY stands for 'Paul Magwene
     Yeast'. These are the actual stocks used during these experiments.
- maxGrowth :: The estimate of maximum population growth for that
     strain and temperature, given in OD/sec
- pointOfMaxGrowthRate :: The time point at which the maximum OD was
     reached
- maxOD :: The maximum OD that was reached during the experiment

** 2016-Maxwell-Magwene-100genomes-temperatures-raw.csv

This file contains the raw OD measurements from the Tecan Sunrise
plate reader. The Tecan exports data in a form that is difficult to
analyze, so rather than including the raw .asc files, the data was
read in and aggregated by the script [[file:process-growth-curves.R]]. To
get the actual raw data in the script, please email the corresponding
author of the paper.

------------------------------------------------------------

- YJM :: The YJM number of the strain. YJM stands for 'Yeast John
     McCusker'. These are the original stocks for the 100 genomes
     collection used throughout these experiments that the PMY numbers
     are derived from
- PMY :: The PMY number of the strain. PMY stands for 'Paul Magwene
     Yeast'. These are the actual stocks used during these experiments.
- filename :: The path to the original raw data file
- platemap :: The path to the original plate map file.
- replicate :: The replicate number of the temperature
- temperature :: The temperature the growth curve was collected at
- row :: The row in the plate
- col :: The column in the plate
- seconds :: The number of seconds elapsed since the start of the experiment
- OD :: The optical density in the well

** 2016-Maxwell-Magwene-mito-morphology-scoring.csv

These data were collected by manually scoring the mitochondrial
morphology of strains containing a mitochondrially localized GFP at
both 30C and 35.5C.

See volume 5 pgs 12 and 14 of Colin Maxwell's lab notebook for the raw
data.

------------------------------------------------------------

- strain :: The CMY number of the strain. CMY stands for Colin Maxwell
     Yeast. see TableS1 for a mapping to the PMY number and genotype
     of the strain.
- temp :: The temperature that the data were collected at
- rep :: The replicate number of the data
- A_threads :: "A" is the original scoring code. "threads" is the
     morphology category.
- C_clumps :: "C" is the original scoring code. "clumps" is the
     morphology category; only clumpy mitochondria present.
- B_clumps-threads :: "B" is the original scoring 
     code. "clumps-threads" is the morphology category; both clumps
     and threads present.
- D_no-mitos :: "D" is the original scoring code. "no-mitos" is the
     morphology category; no mitochondria were observed.

** 2016-Maxwell-Magwene-mito-trackscar.csv

- folder :: The name of the folder containing the original data
- experiment_ID	:: The experiment ID of the data
- counts_file :: The name of the file containing the original data
- sampling :: The method of sampling used -- either "random" or
     "for_age". "Random" means the cells were imaged by moving in a
     transect along the slide and imaging each cell that was positive
     for the first stain. "for_age" means that older cells were sought
     out specifically. 
- temp :: The temperature that the data was collected at.
- media ::
- who_counted ::
- number_of_colors ::
- time ::
- strain ::	
- growth ::	
- first	::
- second ::	
- mitos ::

** 2016-Maxwell-Magwene-three-color-trackscar.csv
** 2016-Maxwell-Magwene-two-color-trackscar-haploid-S288C.csv
** 2016-Maxwell-Magwene-two-color-trackscar-timeseries.csv
** 2016-Maxwell-Magwene-two-color-trackscar.csv
